export const PORTFOLIO_ITEMS = [
  {
    isClosedSource: true,
    codeRepoUrl: "",
    isInternal: true,
    hasCaseStudy: true,
    siteUrl: "",
    name: "Mitre Threat Modeling App",
    infoUrl: "/portfolio/mitre-app",
    image: {
      source: "/images/portfolio/mitre.png",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: true,
    codeRepoUrl: "",
    isInternal: true,
    hasCaseStudy: true,
    siteUrl: "",
    name: "Public Transport Vehicle Surveillance System",
    infoUrl: "/portfolio/survillence",
    image: {
      source: "/images/portfolio/vision.png",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: true,
    codeRepoUrl: "",
    hasCaseStudy: true,
    isInternal: false,
    siteUrl: "https://runningtheroad.ca/",
    name: "Roadrunner",
    infoUrl: "/portfolio/roadrunner",
    image: {
      source: "/images/portfolio/roadrunner.png",
      width: 200,
      height: 200,
    },
  },
  {
    isClosedSource: true,
    codeRepoUrl: "",
    isInternal: true,
    siteUrl: "",
    hasCaseStudy: true,
    name: "Go Ahead",
    infoUrl: "/portfolio/go-ahead",
    image: {
      source: "/images/portfolio/goahead.png",
      width: 200,
      height: 200,
    },
  },
  {
    isClosedSource: true,
    codeRepoUrl: "",
    isInternal: true,
    siteUrl: "",
    hasCaseStudy: true,
    name: "Convey Mobile",
    infoUrl: "/portfolio/cargo",
    image: {
      source: "/images/portfolio/convey.png",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: true,
    codeRepoUrl: "",
    isInternal: true,
    siteUrl: "",
    hasCaseStudy: true,
    name: "Forest Mobile",
    infoUrl: "/portfolio/forest",
    image: {
      source: "/images/portfolio/forest.png",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: false,
    codeRepoUrl: "https://github.com/rucinpk/github-explorer",
    isInternal: false,
    hasCaseStudy: false,
    siteUrl: "https://github-explorer-gmlvkfqjl-rucinpk.vercel.app/",
    name: "Github Repo Explorer",
    infoUrl: "/portfolio/mitre-app",
    image: {
      source: "/images/portfolio/explorer.jpg",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: false,
    codeRepoUrl: "https://github.com/rucinpk/CryptoAPI",
    isInternal: true,
    hasCaseStudy: false,
    siteUrl: "https://github-explorer-gmlvkfqjl-rucinpk.vercel.app/",
    name: "Crypto API",
    infoUrl: "/portfolio/mitre-app",
    image: {
      source: "/images/portfolio/code.jpg",
      width: 400,
      height: 400,
    },
  },
  {
    isClosedSource: false,
    codeRepoUrl: "https://github.com/rucinpk/rust_3ncrypt0r",
    isInternal: true,
    siteUrl: "https://github-explorer-gmlvkfqjl-rucinpk.vercel.app/",
    name: "Rust 3ncrypt0r",
    hasCaseStudy: false,
    infoUrl: "/portfolio/mitre-app",
    image: {
      source: "/images/portfolio/cipher.jpg",
      width: 400,
      height: 400,
    },
  },
];
